SELECT (avg(?count) AS ?avgCount)
{
      SELECT ?year (count(?album) AS ?count) 
      {
            ?album a :Album ;
                  :date ?date ;
            BIND (year(?date) AS ?year)
      } 
      GROUP BY ?year
}